### ISSUE TITLE
Title cut off on mobile

### ISSUE THREAD

**Issue by ckifer** [mascent/james-hoffmann-calculator#4]
Hi, love the calculator. Thank you!

Tiny nitpick is that the words "Hoffman fan made coffee" in the title get cut off when on mobile. 

iOS
Browser: Safari/Chrome

I would submit a PR if I wasn't on mobile! Maybe Monday :). 

Thanks!

**Comment by mascent** [comment]
Should be fixed by #9 :-) thanks for the feedback!

**Comment by ckifer** [comment]
Nice, looking good 👍. Thanks!
